from app.core.exceptions import CustomException


class UserAlreadyExist(CustomException):
    pass
